# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-ast
  - id: check-toml
- repo: https://github.com/rhysd/actionlint
  rev: v1.6.27
  hooks:
  - id: actionlint
- repo: https://github.com/mrtazz/checkmake.git
  rev: 0.2.2
  hooks:
  - id: checkmake
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.1
  hooks:
  - id: ruff
  - id: ruff-format
- repo: https://github.com/crate-ci/typos
  rev: v1.19.0
  hooks:
  - id: typos
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0   # or other specific tag
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --line-width=120

  - id: pretty-format-ini
    args:
    - --autofix

  - id: pretty-format-toml
    args:
    - --autofix
    - --trailing-commas
